//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Labels_Namespace.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpecifyDelimitersAndQualifier {
            get {
                return ((bool)(this["SpecifyDelimitersAndQualifier"]));
            }
            set {
                this["SpecifyDelimitersAndQualifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpecifyFirstColumnName {
            get {
                return ((bool)(this["SpecifyFirstColumnName"]));
            }
            set {
                this["SpecifyFirstColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string DataDelimiter {
            get {
                return ((string)(this["DataDelimiter"]));
            }
            set {
                this["DataDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"")]
        public string DataQualifier {
            get {
                return ((string)(this["DataQualifier"]));
            }
            set {
                this["DataQualifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string DataRepeatFieldDelimiter {
            get {
                return ((string)(this["DataRepeatFieldDelimiter"]));
            }
            set {
                this["DataRepeatFieldDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CALL #(ITEM)")]
        public string DataFirstColumnName {
            get {
                return ((string)(this["DataFirstColumnName"]));
            }
            set {
                this["DataFirstColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string DataDefaultRFD {
            get {
                return ((string)(this["DataDefaultRFD"]));
            }
            set {
                this["DataDefaultRFD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemoveSubFieldIndicators {
            get {
                return ((bool)(this["RemoveSubFieldIndicators"]));
            }
            set {
                this["RemoveSubFieldIndicators"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StackSpaces {
            get {
                return ((bool)(this["StackSpaces"]));
            }
            set {
                this["StackSpaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StackDots {
            get {
                return ((bool)(this["StackDots"]));
            }
            set {
                this["StackDots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UnStackAmpersands {
            get {
                return ((bool)(this["UnStackAmpersands"]));
            }
            set {
                this["UnStackAmpersands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterFirstRepeatOnly {
            get {
                return ((bool)(this["FilterFirstRepeatOnly"]));
            }
            set {
                this["FilterFirstRepeatOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilterIncludeAllRepeats {
            get {
                return ((bool)(this["FilterIncludeAllRepeats"]));
            }
            set {
                this["FilterIncludeAllRepeats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13, 10")]
        public global::System.Drawing.Point SpineAlignmentPanelLocation {
            get {
                return ((global::System.Drawing.Point)(this["SpineAlignmentPanelLocation"]));
            }
            set {
                this["SpineAlignmentPanelLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("228, 10")]
        public global::System.Drawing.Point PocketAlignmentPanelLocation {
            get {
                return ((global::System.Drawing.Point)(this["PocketAlignmentPanelLocation"]));
            }
            set {
                this["PocketAlignmentPanelLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 18pt, style=Bold")]
        public global::System.Drawing.Font SpineFont {
            get {
                return ((global::System.Drawing.Font)(this["SpineFont"]));
            }
            set {
                this["SpineFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 12pt, style=Bold")]
        public global::System.Drawing.Font PocketFont {
            get {
                return ((global::System.Drawing.Font)(this["PocketFont"]));
            }
            set {
                this["PocketFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zebra TLP2844")]
        public string PrinterName {
            get {
                return ((string)(this["PrinterName"]));
            }
            set {
                this["PrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpineAutoMargin {
            get {
                return ((bool)(this["SpineAutoMargin"]));
            }
            set {
                this["SpineAutoMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SpineMargin {
            get {
                return ((global::System.Drawing.Point)(this["SpineMargin"]));
            }
            set {
                this["SpineMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PocketAutoMargin {
            get {
                return ((bool)(this["PocketAutoMargin"]));
            }
            set {
                this["PocketAutoMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PocketMargin {
            get {
                return ((global::System.Drawing.Point)(this["PocketMargin"]));
            }
            set {
                this["PocketMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::System.Windows.Forms.HorizontalAlignment SpineTextAlignment {
            get {
                return ((global::System.Windows.Forms.HorizontalAlignment)(this["SpineTextAlignment"]));
            }
            set {
                this["SpineTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::System.Windows.Forms.HorizontalAlignment PocketTextAlignment {
            get {
                return ((global::System.Windows.Forms.HorizontalAlignment)(this["PocketTextAlignment"]));
            }
            set {
                this["PocketTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool orientSpineLandscape {
            get {
                return ((bool)(this["orientSpineLandscape"]));
            }
            set {
                this["orientSpineLandscape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool orientPocketLandscape {
            get {
                return ((bool)(this["orientPocketLandscape"]));
            }
            set {
                this["orientPocketLandscape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showFontStyles {
            get {
                return ((bool)(this["showFontStyles"]));
            }
            set {
                this["showFontStyles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SierraCleanFields {
            get {
                return ((bool)(this["SierraCleanFields"]));
            }
            set {
                this["SierraCleanFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExpandEscapeChars {
            get {
                return ((bool)(this["ExpandEscapeChars"]));
            }
            set {
                this["ExpandEscapeChars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FillPocketFromDGV {
            get {
                return ((bool)(this["FillPocketFromDGV"]));
            }
            set {
                this["FillPocketFromDGV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WordWrapSpineBox {
            get {
                return ((bool)(this["WordWrapSpineBox"]));
            }
            set {
                this["WordWrapSpineBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WordWrapPocketBox {
            get {
                return ((bool)(this["WordWrapPocketBox"]));
            }
            set {
                this["WordWrapPocketBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sierra.marmot.org/iii/sierra-api/v5/")]
        public string SierraAPI_Server {
            get {
                return ((string)(this["SierraAPI_Server"]));
            }
            set {
                this["SierraAPI_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RPcJh0bvhuFkPPYhJOUuTIPkmTK2")]
        public string SierraAPI_Key {
            get {
                return ((string)(this["SierraAPI_Key"]));
            }
            set {
                this["SierraAPI_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Halloween2019$$")]
        public string SierraAPI_Secret {
            get {
                return ((string)(this["SierraAPI_Secret"]));
            }
            set {
                this["SierraAPI_Secret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n  \"target\": {\"record\": { \"type\": \"item\"}, \"field\": {\"tag\": \"b\"}},\r\n  \"expr\": {" +
            "\"op\": \"equals\",\"operands\": [\"<barcode>\"]}\r\n}")]
        public string BarcodeQuery {
            get {
                return ((string)(this["BarcodeQuery"]));
            }
            set {
                this["BarcodeQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^\\d{13}$")]
        public string BarcodeRegexPattern {
            get {
                return ((string)(this["BarcodeRegexPattern"]));
            }
            set {
                this["BarcodeRegexPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 18pt")]
        public global::System.Drawing.Font QuickFont1 {
            get {
                return ((global::System.Drawing.Font)(this["QuickFont1"]));
            }
            set {
                this["QuickFont1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial Narrow, 18pt, style=Bold")]
        public global::System.Drawing.Font QuickFont2 {
            get {
                return ((global::System.Drawing.Font)(this["QuickFont2"]));
            }
            set {
                this["QuickFont2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 18pt, style=Bold")]
        public global::System.Drawing.Font QuickFont3 {
            get {
                return ((global::System.Drawing.Font)(this["QuickFont3"]));
            }
            set {
                this["QuickFont3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial Black, 18pt, style=Bold")]
        public global::System.Drawing.Font QuickFont4 {
            get {
                return ((global::System.Drawing.Font)(this["QuickFont4"]));
            }
            set {
                this["QuickFont4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public string QuickFontName1 {
            get {
                return ((string)(this["QuickFontName1"]));
            }
            set {
                this["QuickFontName1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Narrow")]
        public string QuickFontName2 {
            get {
                return ((string)(this["QuickFontName2"]));
            }
            set {
                this["QuickFontName2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bold")]
        public string QuickFontName3 {
            get {
                return ((string)(this["QuickFontName3"]));
            }
            set {
                this["QuickFontName3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string QuickFontName4 {
            get {
                return ((string)(this["QuickFontName4"]));
            }
            set {
                this["QuickFontName4"] = value;
            }
        }
    }
}
